### ISSUE TITLE
No CI pipelines for code verification

### ISSUE THREAD

**Issue by rufferson** [TelepathyIM/wocky#17]
ditto

**Comment by rufferson** [comment]
Oh, I didn't realize actions are not available on this repo. Either way will help when someone clones and commits

**Comment by Kaffeine** [comment]
> Oh, I didn't realize actions are not available on this repo. Either way will help when someone clones and commits

I don't see the reason why the actions disabled, so I enabled them.

**Comment by Kaffeine** [comment]
Maybe I disabled them to hide unused tabs. I would prefer to also disable/hide `Projects` and `wiki` if you don't need them (it is fine to get them back when needed).
Please confirm that you don't need them so I hide those two.

**Comment by rufferson** [comment]
Thanks!
I can't think of any use for projects but I was planning to submit some internals doc to wiki
